[project]
name = "boomerang"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiohttp>=3.12.15",
    "alpha-vantage>=3.0.0",
    "crewai>=0.165.1",
    "fastapi>=0.116.1",
    "finvizfinance>=1.1.1",
    "ipykernel>=6.30.1",
    "jupyter>=1.1.1",
    "llama-index>=0.13.3",
    "matplotlib>=3.10.5",
    "openai>=1.99.9",
    "pandas>=2.2.3",
    "plotly>=6.3.0",
    "pydantic>=2.11.7",
    "requests>=2.32.5",
    "scikit-learn>=1.7.1",
    "seaborn>=0.13.2",
    "sqlalchemy>=2.0.43",
    "statsmodels>=0.14.5",
    "ta>=0.11.0",
    "torch>=2.8.0",
    "uvicorn>=0.35.0",
    "websockets>=15.0.1",
    "yfinance>=0.2.65",
]
